name: Nightly test execution

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: 'dev'
        description: Select an environment
        type: choice
        options:
          - dev
          - staging
          - production

jobs:
  smoke-tests:
    name: Smoke tests
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        run: echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - name: Print a message
        run: echo "Running test on ${{ ENVIRONMENT }}"